"""Linear issue writer for Sky-Lynx recommendations.

Creates Linear issues for each recommendation so Matthew has visibility
in the Linear UI. Uses the Arcade Python SDK (same pattern as Metroplex).

Env vars:
    ARCADE_API_KEY: Arcade gateway key
    ARCADE_USER_ID: Arcade user context
    SKYLYNX_LINEAR_TEAM: Linear team name (required to create issues)
    SKYLYNX_LINEAR_LABEL: Label to apply (default: sky-lynx)
"""

from __future__ import annotations

import logging
import os
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .claude_client import Recommendation

logger = logging.getLogger(__name__)

try:
    from arcadepy import Arcade
except ImportError:
    Arcade = None

# Map Sky-Lynx priority to Linear priority integers
# Linear: 1=urgent, 2=high, 3=medium, 4=low, 0=none
PRIORITY_MAP = {
    "high": 2,
    "medium": 3,
    "low": 4,
}


def create_linear_issues(
    recommendations: list[Recommendation],
    session_id: str,
    dry_run: bool = False,
) -> list[str]:
    """Create Linear issues from Sky-Lynx recommendations.

    Args:
        recommendations: List of Recommendation objects from analysis
        session_id: Sky-Lynx session ID for traceability
        dry_run: If True, log but don't create issues

    Returns:
        List of created Linear issue identifiers
    """
    if not recommendations:
        return []

    if Arcade is None:
        logger.warning(
            "arcadepy not installed — skipping Linear issue creation"
        )
        return []

    api_key = os.environ.get("ARCADE_API_KEY", "")
    user_id = os.environ.get("ARCADE_USER_ID", "agent@local")
    team = os.environ.get("SKYLYNX_LINEAR_TEAM", "")
    label = os.environ.get("SKYLYNX_LINEAR_LABEL", "sky-lynx")

    if not api_key:
        logger.warning(
            "ARCADE_API_KEY not set — skipping Linear issue creation"
        )
        return []

    if not team:
        logger.info(
            "SKYLYNX_LINEAR_TEAM not set — skipping Linear issue creation"
        )
        return []

    client = Arcade(api_key=api_key)
    created: list[str] = []

    for rec in recommendations:
        title = f"[Sky-Lynx] {rec.title}"
        priority = PRIORITY_MAP.get(rec.priority, 3)
        description = _format_issue_body(rec, session_id)

        if dry_run:
            logger.info(f"  [DRY RUN] Would create: {title}")
            created.append(f"DRY-{rec.recommendation_id or rec.title[:20]}")
            continue

        try:
            params: dict[str, object] = {
                "title": title,
                "description": description,
                "priority": priority,
                "team": team,
            }
            if label:
                params["label"] = label

            result = client.tools.execute(
                tool_name="Linear_CreateIssue",
                input=params,
                user_id=user_id,
            )

            raw = result.output.value
            identifier = ""
            if isinstance(raw, dict):
                issue = raw.get("issue", raw)
                identifier = issue.get("identifier", "")

            if identifier:
                created.append(identifier)
                logger.info(f"  Created Linear issue {identifier}: {title}")
            else:
                logger.warning(
                    f"  Created issue but no identifier returned: {title}"
                )

        except Exception as e:
            logger.warning(f"  Failed to create Linear issue '{title}': {e}")
            continue

    return created


def _format_issue_body(rec: Recommendation, session_id: str) -> str:
    """Format a Recommendation into a Linear issue body.

    Args:
        rec: Recommendation object
        session_id: Sky-Lynx session identifier

    Returns:
        Markdown-formatted issue body
    """
    lines = [
        f"**Source**: Sky-Lynx weekly analysis (`{session_id}`)",
        f"**Priority**: {rec.priority}",
        f"**Type**: {rec.recommendation_type}",
        f"**Target**: {rec.target_system}",
        "",
    ]

    if rec.evidence:
        lines.extend(["## Evidence", rec.evidence, ""])

    if rec.suggested_change:
        lines.extend(["## Suggested Change", rec.suggested_change, ""])

    if rec.impact:
        lines.extend(["## Expected Impact", rec.impact, ""])

    rec_id = rec.recommendation_id or "N/A"
    lines.append(
        f"\n---\n*Auto-generated by Sky-Lynx. "
        f"Recommendation ID: {rec_id}*"
    )

    return "\n".join(lines)
