"""PR drafter for Sky-Lynx.

Creates draft PRs with proposed CLAUDE.md changes using the gh CLI.
"""

import os
import subprocess
from datetime import datetime
from pathlib import Path
from tempfile import NamedTemporaryFile

from .claude_client import AnalysisResult


def get_claude_md_path() -> Path:
    """Get the path to the user's CLAUDE.md file.

    Returns:
        Path to ~/CLAUDE.md
    """
    return Path.home() / "CLAUDE.md"


def get_branch_name() -> str:
    """Generate a branch name for today's recommendations.

    Returns:
        Branch name like "sky-lynx/2026-02-05"
    """
    today = datetime.now().strftime("%Y-%m-%d")
    return f"sky-lynx/{today}"


def run_gh_command(args: list[str], check: bool = True) -> subprocess.CompletedProcess[str]:
    """Run a gh CLI command.

    Args:
        args: Command arguments (excluding 'gh')
        check: Whether to raise on non-zero exit

    Returns:
        CompletedProcess result
    """
    cmd = ["gh"] + args
    return subprocess.run(cmd, capture_output=True, text=True, check=check)


def check_gh_available() -> bool:
    """Check if gh CLI is available and authenticated.

    Returns:
        True if gh is available and authenticated
    """
    try:
        result = run_gh_command(["auth", "status"], check=False)
        return result.returncode == 0
    except FileNotFoundError:
        return False


def generate_claude_md_changes(
    analysis: AnalysisResult,
    exclude_titles: set[str] | None = None,
) -> str | None:
    """Generate proposed additions to CLAUDE.md based on recommendations.

    Args:
        analysis: AnalysisResult from Claude
        exclude_titles: Titles to skip (already auto-applied)

    Returns:
        Proposed text to add, or None if no changes suggested
    """
    if not analysis.recommendations:
        return None

    exclude = exclude_titles or set()

    # Filter to high priority recommendations only, excluding auto-applied
    high_priority = [
        r for r in analysis.recommendations
        if r.priority == "high" and r.title not in exclude
    ]

    if not high_priority:
        return None

    today = datetime.now().strftime("%Y-%m-%d")
    lines = [
        "",
        f"## Sky-Lynx Recommendations ({today})",
        "",
        "_The following suggestions were generated by Sky-Lynx based on usage pattern analysis._",
        "",
    ]

    for rec in high_priority:
        lines.append(f"### {rec.title}")
        lines.append("")
        if rec.suggested_change:
            # Try to extract actionable content
            lines.append(rec.suggested_change)
        else:
            lines.append(f"- Evidence: {rec.evidence}")
        lines.append("")

    return "\n".join(lines)


def create_draft_pr(
    analysis: AnalysisResult,
    dry_run: bool = False,
    exclude_titles: set[str] | None = None,
) -> str | None:
    """Create a draft PR with proposed CLAUDE.md changes.

    Args:
        analysis: AnalysisResult from Claude
        dry_run: If True, don't actually create PR
        exclude_titles: Titles to skip (already auto-applied)

    Returns:
        PR URL if created, None otherwise
    """
    # Generate proposed changes
    changes = generate_claude_md_changes(analysis, exclude_titles=exclude_titles)
    if not changes:
        return None

    if dry_run:
        print(f"[DRY RUN] Would propose changes:\n{changes}")
        return None

    # Check gh availability
    if not check_gh_available():
        print("Warning: gh CLI not available or not authenticated. Skipping PR creation.")
        return None

    claude_md = get_claude_md_path()
    if not claude_md.exists():
        print(f"Warning: {claude_md} not found. Skipping PR creation.")
        return None

    # Check if we're in a git repo
    home = Path.home()
    git_dir = home / ".git"
    if not git_dir.exists():
        # Home directory is not a git repo - this is expected
        # We'd need a different approach for non-repo CLAUDE.md
        print("Note: Home directory is not a git repo. Skipping PR creation.")
        print("To enable PR creation, initialize a git repo for your dotfiles.")
        return None

    branch_name = get_branch_name()

    try:
        # Create branch
        subprocess.run(
            ["git", "-C", str(home), "checkout", "-b", branch_name],
            capture_output=True,
            text=True,
            check=True,
        )

        # Read current CLAUDE.md
        current_content = claude_md.read_text()

        # Append changes
        new_content = current_content + changes
        claude_md.write_text(new_content)

        # Stage and commit
        subprocess.run(
            ["git", "-C", str(home), "add", "CLAUDE.md"],
            capture_output=True,
            text=True,
            check=True,
        )

        today = datetime.now().strftime("%Y-%m-%d")
        commit_msg = f"feat: Sky-Lynx recommendations ({today})"
        subprocess.run(
            ["git", "-C", str(home), "commit", "-m", commit_msg],
            capture_output=True,
            text=True,
            check=True,
        )

        # Push branch
        subprocess.run(
            ["git", "-C", str(home), "push", "-u", "origin", branch_name],
            capture_output=True,
            text=True,
            check=True,
        )

        # Create draft PR
        result = run_gh_command(
            [
                "pr",
                "create",
                "--draft",
                "--title",
                f"Sky-Lynx: Weekly CLAUDE.md improvements ({today})",
                "--body",
                _generate_pr_body(analysis),
            ]
        )

        # Extract PR URL from output
        pr_url = result.stdout.strip()

        # Switch back to main branch
        subprocess.run(
            ["git", "-C", str(home), "checkout", "main"],
            capture_output=True,
            text=True,
            check=False,  # Don't fail if main doesn't exist
        )

        return pr_url

    except subprocess.CalledProcessError as e:
        print(f"Warning: Failed to create PR: {e}")
        print(f"stdout: {e.stdout}")
        print(f"stderr: {e.stderr}")

        # Try to recover - go back to main
        subprocess.run(
            ["git", "-C", str(home), "checkout", "main"],
            capture_output=True,
            text=True,
            check=False,
        )

        # Delete the failed branch
        subprocess.run(
            ["git", "-C", str(home), "branch", "-D", branch_name],
            capture_output=True,
            text=True,
            check=False,
        )

        return None


def _generate_pr_body(analysis: AnalysisResult) -> str:
    """Generate the PR body content.

    Args:
        analysis: AnalysisResult

    Returns:
        PR body markdown
    """
    lines = [
        "## Summary",
        "",
        "Weekly CLAUDE.md improvement recommendations generated by Sky-Lynx.",
        "",
        "### Executive Summary",
        "",
        analysis.executive_summary or "_No summary available._",
        "",
        "### Recommendations Included",
        "",
    ]

    high_priority = [r for r in analysis.recommendations if r.priority == "high"]
    for rec in high_priority:
        lines.append(f"- **{rec.title}**")
        if rec.evidence:
            lines.append(f"  - Evidence: {rec.evidence}")

    lines.extend(
        [
            "",
            "---",
            "",
            "_Generated by [Sky-Lynx](https://github.com/m2ai-portfolio/sky-lynx)_",
        ]
    )

    return "\n".join(lines)
